### PR TITLE
Fix for invalid template issue #9

### PR DESCRIPTION
**Pull request by ankit-ls**
This PR fixes issue #9 .

It removes the unicode character `<U+200B>` which was introduced in PR #8 .

Screenshot 2021-08-19 at 3 39 56 PM

### CODE REVIEW

**Comment by ankit-ls** [comment]
@plmercereau @preiddygarcia It would be great if you could merge and release a patch for this, as we want to use this for multiple namespaces.

**Review by plmercereau — CHANGES_REQUESTED** [review]
would you mind incrementing versions in the `Chart.yaml` files to make it a patch release according to semantic versioning?

**Comment by ankit-ls** [comment]
@plmercereau Done!

**Comment by plmercereau** [comment]
Many thanks for this PR!

**Pull request merged**
